version: '3'
services:
  app:
    image: xahmedmahmoudx/instabug:latest
    ports:
      - 9090:9090
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASS=1234
      - MYSQL_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
