apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  MYSQL_HOST: {{ .Values.mysql.host }}
  MYSQL_USER: {{ .Values.mysql.user }}
  MYSQL_PASS: {{ .Values.mysql.password }}
  MYSQL_PORT: {{ .Values.mysql.port }}
